### ISSUE TITLE
Feature request for wiki-proxy: Provide keys for other firmware components (<=iOS 9/32-bit compatibility)

### ISSUE THREAD

**Issue by LukeZGD** [m1stadev/ios-tools#4]
Currently, wiki-proxy only provides firmware keys for `iBSS`, `iBEC`, `iBoot`, `LLB`, and `SEPFirmware`, which works fine for futurerestoring to iOS 10 and newer. But restores to iOS 9 and below would fail because libipatcher is expected to decrypt all images (including `AppleLogo` and other components) for pwned DFU restores ([as explained by Cryptic](https://discord.com/channels/349243932447604736/688124783400845336/905354661995880478))

This issue is more of a feature request for wiki-proxy to be able to provide the other firmware keys for <=iOS 9 and 32-bit compatibility, so that it may also be implemented in your wikiproxy API that libipatcher/futurerestore uses

**Comment by m1stadev** [comment]
Completely forgot about that while I was rewriting wikiproxy, I'll get on that.

**Comment by m1stadev** [comment]
Done in 7fd73b7.
